set_property SRC_FILE_INFO {cfile:C:/Users/tau/Downloads/lab09/lab09/lab09.srcs/constrs_1/new/constraints.xdc rfile:../lab09.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports btn_next]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports btn_next]
