## Clock (100MHz)
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Reset (Center button)
set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

## LEDs [15:0]
set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN W18 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN U15 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN U14 [get_ports {LEDs[6]}]
set_property PACKAGE_PIN V14 [get_ports {LEDs[7]}]
set_property PACKAGE_PIN V13 [get_ports {LEDs[8]}]
set_property PACKAGE_PIN V3  [get_ports {LEDs[9]}]
set_property PACKAGE_PIN W3  [get_ports {LEDs[10]}]
set_property PACKAGE_PIN U3  [get_ports {LEDs[11]}]
set_property PACKAGE_PIN P3  [get_ports {LEDs[12]}]
set_property PACKAGE_PIN N3  [get_ports {LEDs[13]}]
set_property PACKAGE_PIN P1  [get_ports {LEDs[14]}]
set_property PACKAGE_PIN L1  [get_ports {LEDs[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[*]}]
## Switches (UNUSED UNTILL TASK3)
#set_property PACKAGE_PIN V17 [get_ports {SW[0]}]
#set_property PACKAGE_PIN V16 [get_ports {SW[1]}]
#set_property PACKAGE_PIN W16 [get_ports {SW[2]}]
#set_property PACKAGE_PIN W17 [get_ports {SW[3]}]
#set_property PACKAGE_PIN W15 [get_ports {SW[4]}]
#set_property PACKAGE_PIN V15 [get_ports {SW[5]}]
#set_property PACKAGE_PIN W14 [get_ports {SW[6]}]
#set_property PACKAGE_PIN W13 [get_ports {SW[7]}]
#set_property PACKAGE_PIN V2  [get_ports {SW[8]}]
#set_property PACKAGE_PIN T3  [get_ports {SW[9]}]
#set_property PACKAGE_PIN T2  [get_ports {SW[10]}]
#set_property PACKAGE_PIN R3  [get_ports {SW[11]}]
#set_property PACKAGE_PIN W2  [get_ports {SW[12]}]
#set_property PACKAGE_PIN U1  [get_ports {SW[13]}]
#set_property PACKAGE_PIN T1  [get_ports {SW[14]}]
#set_property PACKAGE_PIN R2  [get_ports {SW[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SW[*]}]

## Seven Segment Display
set_property PACKAGE_PIN W7  [get_ports {seg[0]}]
set_property PACKAGE_PIN W6  [get_ports {seg[1]}]
set_property PACKAGE_PIN U8  [get_ports {seg[2]}]
set_property PACKAGE_PIN V8  [get_ports {seg[3]}]
set_property PACKAGE_PIN U5  [get_ports {seg[4]}]
set_property PACKAGE_PIN V5  [get_ports {seg[5]}]
set_property PACKAGE_PIN U7  [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[*]}]

set_property PACKAGE_PIN U2  [get_ports {an[0]}]
set_property PACKAGE_PIN U4  [get_ports {an[1]}]
set_property PACKAGE_PIN V4  [get_ports {an[2]}]
set_property PACKAGE_PIN W4  [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[*]}]

set_property PACKAGE_PIN V7  [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports dp]