## Clock (100MHz)
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Reset (Center button)
set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

## LEDs [15:0]
set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN W18 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN U15 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN U14 [get_ports {LEDs[6]}]
set_property PACKAGE_PIN V14 [get_ports {LEDs[7]}]
set_property PACKAGE_PIN V13 [get_ports {LEDs[8]}]
set_property PACKAGE_PIN V3  [get_ports {LEDs[9]}]
set_property PACKAGE_PIN W3  [get_ports {LEDs[10]}]
set_property PACKAGE_PIN U3  [get_ports {LEDs[11]}]
set_property PACKAGE_PIN P3  [get_ports {LEDs[12]}]
set_property PACKAGE_PIN N3  [get_ports {LEDs[13]}]
set_property PACKAGE_PIN P1  [get_ports {LEDs[14]}]
set_property PACKAGE_PIN L1  [get_ports {LEDs[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[*]}]
set_property PACKAGE_PIN U16 [get_ports dummy]
set_property IOSTANDARD LVCMOS33 [get_ports dummy]